title: 'Website Title'
default_lang: de
author:
  name: ''
  email: ''
metadata:
  generator: ''
  description: ''
summary:
  enabled: true
  format: short
  size: 200
  delimiter: '==='
blog:
  route: /blog
taxonomies:
  - navarea
