title: 'Website Title'
default_lang: de
author:
  name: 'Joe Bloggs'
  email: joe@example.com
metadata:
  generator: ''
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 200
  delimiter: '==='
blog:
  route: /blog

footer:
  menu:
    - title: Startseite
      url: /
    - title: Impressum
      url: /impressum
    - title: Datenschutz
      url: /datenschutz
  social:
    - title: Facebook
      icon: facebook
      url: http://www.facebook.com/XX
    - title: Instagram
      icon: instagram
      url: https://www.instagram.com/XX
    - title: Twitter
      icon: twitter
      url: http://www.twitter.com/XX
    - title: Xing
      icon: xing
      url: http://www.xing.com/XX
    - title: YouTube
      icon: youtube
      url: https://www.youtube.com/XX