home:
  alias: '/home'

pages:
  theme: quark
  markdown:
    extra: true
  process:
    markdown: true
    twig: true
  frontmatter:
    process_twig: true

session:
  initialize: false
  name: grav-site

cache:
  gzip: true

images:
  default_image_quality: 70
  defaults:
    loading: lazy

pwd_regex: '^[ -~]{8,}$'

env:
  state: production