cache:
  enabled: false

debugger:
  enabled: true
  twig: true
  shutdown:
    close_connection: true

errors:
  display: true
  log: true

dev_mode: true
# let's use 3 character passwords on dev
pwd_regex: '^[ -~]{3,}$'